<!DOCTYPE html>
<html>
    <body>
        <h1>New Car</h1>

        <div>
            <a href="/">cars list</a>
        </div>

        <br>

        <!-- BEGIN (write your solution here) -->
        <form action="/cars" method="post">
            <div>
                <b>Model</b>
                <input type="text" name="car[model]">
                <?php if (isset($errors['model'])) : ?>
                    <div style="color: red"><?= $errors['model'] ?></div>
                <?php endif ?>
            </div>

            <br>

            <div>
                Year
                <input type="number" name="car[year]">
            </div><br>
            <div>
                <input type="submit">
            </div>
        </form>
        <!-- END -->

    </body>
</html>
